doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: true
        mappings:
            Invoice:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Invoice/Domain'
                prefix: App\Core\Invoice\Domain\Invoice
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/User/Domain'
                prefix: App\Core\User\Domain\User

when@test:
    doctrine:
        dbal:
            default_connection: default
            connections:
                default:
                    use_savepoints: true

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
