services:
  ak_invoice_php:
    container_name: ak_invoice_php
    restart: always
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    ports:
      - '8011:80'
    depends_on:
      - ak_invoice_mysql
    volumes:
      - .:/var/www/html
      - ./docker/build/php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/build/php/conf.d/docker-php-memlimit.ini:/usr/local/etc/php/conf.d/docker-php-memlimit.ini

  ak_invoice_mysql:
    container_name: ak_invoice_mysql
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    expose:
      - '3306'
    ports:
      - '33075:3306'
    volumes:
      - ./docker/build/mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
